version: '3'
services:
  redis:
    image: 'redislabs/redisearch:latest'
    container_name: 'redis'
    command: bash -c "redis-server --appendonly yes --requirepass mypassword"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a mypassword ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - ./redis-volume:/data
  
  alarm_service:
    build:
      context: .
      dockerfile: deployable projects/AlarmService/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy