name: delivery

on:
  push:
    branches: [ continuous-delivery ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  get-last-version-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve last image version for Gateway
        id: get_version_gateway
        run: |
          LAST_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/magnusovergaard/gateway/tags/?page_size=1 | jq -r '.results[0].name' | cut -d'-' -f2)
          echo "::set-output name=LAST_VERSION::$LAST_VERSION"
  build-and-push-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/Gateway/Dockerfile
          push: true
          tags: magnusovergaard/gateway:latest, magnusovergaard/gateway:${{ steps.get_version_gateway.outputs.LAST_VERSION + 1 }}
          
  build-and-push-alarm_api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
          
      - name: Build and push AlarmAPI
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/AlarmAPI/Dockerfile
          push: true
          tags: magnusovergaard/alarm-api:latest
          
  build-and-push-alarm_consumer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push AlarmConsumer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/AlarmConsumer/Dockerfile
          push: true
          tags: magnusovergaard/alarm_consumer:latest
          
  build-and-push-location-consumer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push LocationConsumer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/LocationConsumer/Dockerfile
          push: true
          tags: magnusovergaard/location-consumer:latest
          
  build-and-push-location-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push LocationAPI
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/LocationAPI/Dockerfile
          push: true
          tags: magnusovergaard/location-api:latest
          
  build-and-push-location-retrieval-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push LocationRetrievalApi
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployable projects/LocationRetrievalApi/Dockerfile
          push: true
          tags: magnusovergaard/location-retrieval-api:latest
