on:
  workflow_call: 
    
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Retrieve last image version
        id: get_version
        run: |
          response=$(curl -s ${{ inputs.url }})
          last_version=$(echo "$response" | jq -r '.results[0].name' | cut -d'-' -f2 | tr -d '"')
          new_version=$((last_version + 1))
          tag="${{ inputs.image_name }}:$new_version"
          echo "New version: $new_version"
          echo "Tag: $tag"
          echo "::set-output name=tag::$tag"